### ISSUE TITLE
Local OIDC Provider - Cannot get example running

### ISSUE THREAD

**Issue by jontro** [pomerium/pomerium#3602]
## What happened?
After following the guide at https://www.pomerium.com/docs/guides/local-oidc I run into issues with the identity provier reporting errors after setup.

docker-compose logs -f shows the follwing error in the logs:
```identityprovider_1  | (node:1) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: id must be provided to Session#find
identityprovider_1  |     at Function.find (/usr/src/app/node_modules/oidc-provider/lib/models/session.js:82:7)
identityprovider_1  |     at Provider.getInteraction (/usr/src/app/node_modules/oidc-provider/lib/provider.js:62:42)
identityprovider_1  |     at Provider.interactionDetails (/usr/src/app/node_modules/oidc-provider/lib/provider.js:189:46)
identityprovider_1  |     at _0x960b95 (/usr/src/app/server/interactions.js:1:1248)
identityprovider_1  |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
identityprovider_1  |     at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
identityprovider_1  |     at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3)
identityprovider_1  |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
identityprovider_1  |     at /usr/src/app/node_modules/express/lib/router/index.js:281:22
identityprovider_1  |     at param (/usr/src/app/node_modules/express/lib/router/index.js:354:14) 
```

The web page redirects from pomerium to the identity provider which just stalls the connection.

## What did you expect to happen?
That it would successfully work

## How'd it happen?
Set up according to guide. 
Run docker-compose up -d. 
Navigate to https://verify.localhost.pomerium.io in a browser and watch the connection stall.

## What's your environment like?

- Pomerium version (pomerium/pomerium:latest)
Docker version 20.10.16, build aa7e414
MacOS

**Comment by jontro** [comment]
Pinning the version of qlik/simple-oidc-provider to 0.2.2 solves the issue for me. I'm not sure using qlik/simple-oidc-provider  is a good idea to begin with, it's not an open source project, see https://github.com/qlik-oss/dockerfiles/issues/86.

**Comment by desimone** [comment]
Hey @jontro,

Thanks for making the issue.  I don't have a great sense of history about why the repo started OSS but no longer is now.  Some other options:

- https://github.com/keycloak/keycloak
- https://github.com/ory/hydra

We'd very much welcome any community contribution for either. 


Related:

- https://github.com/pomerium/pomerium/issues/3592
- https://github.com/pomerium/pomerium/issues/298

**Comment by pentiak** [comment]
Hey @jontro. How did you get groups claim mapping to work?

> I managed to get it running after pinning the version. Also to get the groups working I had to make a hack to change the claim_mapping of profile to group in identityprovider.json

**Comment by jontro** [comment]
> Hey @jontro. How did you get groups claim mapping to work?
> 

In the claim mapping I mapped profile to groups
```
  "claim_mapping": {
    "openid": [ "sub" ],
    "email": [ "email", "email_verified" ],
    "profile": [ "groups"]
  }

```
Then it worked out of the box with the groups field in `identity-provider-users.json`

`"groups": ["group-1","group-2"] etc`

Not sure why this works though, feels like a hack. The group appears in the payload as a group claim after this change.
