### ISSUE TITLE
panic: runtime error: invalid memory address in getChallengeInfo

### ISSUE THREAD

**Issue by drewp** [pomerium/pomerium#3806]
## What happened?

I can get this:

```
2022/12/12 22:13:32 http: panic serving 10.42.1.0:31159: runtime error: invalid memory address or nil pointer dereference

goroutine 1855 [running]:

net/http.(*conn).serve.func1()

	/usr/local/go/src/net/http/server.go:1850 +0xbf

panic({0x24854c0, 0x82b6770})

	/usr/local/go/src/runtime/panic.go:890 +0x262

github.com/caddyserver/certmagic.(*Config).getChallengeInfo(0x0, {0x303b420, 0xc00148d5c0}, {0xc00165e1c1, 0x1c})

	/go/pkg/mod/github.com/caddyserver/certmagic@v0.17.2/config.go:970 +0x155

github.com/caddyserver/certmagic.(*ACMEIssuer).distributedHTTPChallengeSolver(0xc000de85a0, {0x3038900, 0xc000a7a460}, 0xc002617900)

	/go/pkg/mod/github.com/caddyserver/certmagic@v0.17.2/httphandler.go:74 +0x136

github.com/caddyserver/certmagic.(*ACMEIssuer).HandleHTTPChallenge(0xc000de85a0?, {0x3038900?, 0xc000a7a460?}, 0xc002617900?)

	/go/pkg/mod/github.com/caddyserver/certmagic@v0.17.2/httphandler.go:62 +0xb2

github.com/pomerium/pomerium/internal/autocert.(*Manager).handleHTTPChallenge(0xffffffffffffffff?, {0x3038900, 0xc000a7a460}, 0x0?)

	/go/pkg/mod/github.com/pomerium/pomerium@v0.20.1-0.20221205161217-df508f6bcc74/internal/autocert/manager.go:360 +0x4d

github.com/pomerium/pomerium/internal/autocert.(*Manager).updateServer.func1({0x3038900, 0xc000a7a460}, 0x7fe751d6ff38?)

	/go/pkg/mod/github.com/pomerium/pomerium@v0.20.1-0.20221205161217-df508f6bcc74/internal/autocert/manager.go:315 +0x4a

net/http.HandlerFunc.ServeHTTP(0x0?, {0x3038900?, 0xc000a7a460?}, 0x46c42e?)

	/usr/local/go/src/net/http/server.go:2109 +0x2f

net/http.serverHandler.ServeHTTP({0xc000fb4390?}, {0x3038900, 0xc000a7a460}, 0xc002617900)

	/usr/local/go/src/net/http/server.go:2947 +0x30c

net/http.(*conn).serve(0xc000ef2aa0, {0x303b4c8, 0xc000c630e0})

	/usr/local/go/src/net/http/server.go:1991 +0x607

created by net/http.(*Server).Serve

	/usr/local/go/src/net/http/server.go:3102 +0x4db

```

## What did you expect to happen?

A clearer error about what's wrong with my config.

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`): pomerium/ingress-controller:sha-efe2d11
- Server Operating System/Architecture/Cloud: amd64 local k8s

**Comment by wasaga** [comment]
autocert should be disabled in the k8s environment. apparently it's still running behind the scenes.

```
{"level":"info","service":"autocert-manager","addr":":8080","time":"2022-12-13T23:44:11Z","message":"starting http redirect server"}
```
