### ISSUE TITLE
authenticate service crashing on logout after upgrade from 0.5.2 to 0.6.0

### ISSUE THREAD

**Issue by victornoel** [pomerium/pomerium#530]
## What happened?

I bumped the version of the helm chart from 4.1.4 (pomerium 0.5.2) to 6.0.0 (pomerium 0.6.0) and while everything seems to work as expected, when I do a logout, I get the following error coming from the authenticate service in my browser (on the url `/.pomerium/sign_out?xxxxx`): 
```
upstream connect error or disconnect/reset before headers. reset reason: connection termination
```

And the following in the logs of the authenticate service:
```json
{
    "level": "error",
    "addr": ":443",
    "time": "2020-03-08T14:45:29Z",
    "message": "http: panic serving 10.242.2.3:48750: runtime error: invalid memory address or nil pointer dereference\ngoroutine 242 [running]:\nnet/http.(*conn).serve.func1(0xc0000cba40)\n\t/usr/local/go/src/net/http/server.go:1767 +0x139\npanic(0xdf66a0, 0x1724680)\n\t/usr/local/go/src/runtime/panic.go:679 +0x1b2\ngithub.com/pomerium/pomerium/internal/identity.(*GoogleProvider).Revoke(0xc0001d4140, 0x10a1920, 0xc000363ce0, 0x0, 0x0, 0xe95720)\n\t/go/src/github.com/pomerium/pomerium/internal/identity/google.go:103 +0x93\ngithub.com/pomerium/pomerium/authenticate.(*Authenticate).SignOut(0xc0000ab6c0, 0x7f1aec8d5ac8, 0xc00037a540, 0xc000367700, 0x46802c, 0xdefa40)\n\t/go/src/github.com/pomerium/pomerium/authenticate/handlers.go:205 +0x174\ngithub.com/pomerium/pomerium/internal/httputil.HandlerFunc.ServeHTTP(0xc00021b250, 0x7f1aec8d5ac8, 0xc00037a540, 0xc000367700)\n\t/go/src/github.com/pomerium/pomerium/internal/httputil/handlers.go:40 +0x48\ngithub.com/pomerium/pomerium/authenticate.(*Authenticate).VerifySession.func1(0x7f1aec8d5ac8, 0xc00037a540, 0xc000367700, 0x40c698, 0x80)\n\t/go/src/github.com/pomerium/pomerium/authenticate/handlers.go:90 +0x213\ngithub.com/pomerium/pomerium/internal/httputil.HandlerFunc.ServeHTTP(0xc0001d4240, 0x7f1aec8d5ac8, 0xc00037a540, 0xc000367700)\n\t/go/src/github.com/pomerium/pomerium/internal/httputil/handlers.go:40 +0x48\ngithub.com/pomerium/pomerium/internal/sessions.retrieve.func1.1(0x7f1aec8d5ac8, 0xc00037a540, 0xc000367600)\n\t/go/src/github.com/pomerium/pomerium/internal/sessions/middleware.go:31 +0x1a1\nnet/http.HandlerFunc.ServeHTTP(0xc0003634d0, 0x7f1aec8d5ac8, 0xc00037a540, 0xc000367600)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\ngithub.com/pomerium/pomerium/internal/middleware.ValidateSignature.func1.1(0x7f1aec8d5ac8, 0xc00037a540, 0xc000367500, 0x0, 0x0)\n\t/go/src/github.com/pomerium/pomerium/internal/middleware/middleware.go:37 +0x217\ngithub.com/pomerium/pomerium/internal/httputil.HandlerFunc.ServeHTTP(0xc000363500, 0x7f1aec8d5ac8, 0xc00037a540, 0xc000367500)\n\t/go/src/github.com/pomerium/pomerium/internal/httputil/handlers.go:40 +0x48\ngithub.com/rs/cors.(*Cors).Handler.func1(0x7f1aec8d5ac8, 0xc00037a540, 0xc000367500)\n\t/go/pkg/mod/github.com/rs/cors@v1.7.0/cors.go:219 +0x1b8\nnet/http.HandlerFunc.ServeHTTP(0xc0001d42c0, 0x7f1aec8d5ac8, 0xc00037a540, 0xc000367500)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\ngithub.com/pomerium/csrf.(*csrf).ServeHTTP(0xc00020e0e0, 0x7f1aec8d5ac8, 0xc00037a540, 0xc000367400)\n\t/go/pkg/mod/github.com/pomerium/csrf@v1.6.2-0.20190918035251-f3318380bad3/csrf.go:286 +0x511\ngithub.com/pomerium/pomerium/internal/middleware.SetHeaders.func1.1(0x7f1aec8d5ac8, 0xc00037a540, 0xc000367200)\n\t/go/src/github.com/pomerium/pomerium/internal/middleware/middleware.go:22 +0x388\nnet/http.HandlerFunc.ServeHTTP(0xc0001d42e0, 0x7f1aec8d5ac8, 0xc00037a540, 0xc000367200)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\ngithub.com/gorilla/mux.(*Router).ServeHTTP(0xc000478240, 0x7f1aec8d5ac8, 0xc00037a540, 0xc000367000)\n\t/go/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:212 +0xe2\ngithub.com/pomerium/pomerium/internal/middleware.Healthcheck.func1.1(0x7f1aec8d5ac8, 0xc00037a540, 0xc000366f00)\n\t/go/src/github.com/pomerium/pomerium/internal/middleware/middleware.go:72 +0x4b0\nnet/http.HandlerFunc.ServeHTTP(0xc00037a1c0, 0x7f1aec8d5ac8, 0xc00037a540, 0xc000366f00)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\ngithub.com/pomerium/pomerium/internal/log.RequestIDHandler.func1.1(0x7f1aec8d5ac8, 0xc00037a540, 0xc000366f00)\n\t/go/src/github.com/pomerium/pomerium/internal/log/middleware.go:157 +0x133\nnet/http.HandlerFunc.ServeHTTP(0xc00037a200, 0x7f1aec8d5ac8, 0xc00037a540, 0xc000366e00)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\ngithub.com/pomerium/pomerium/internal/log.RefererHandler.func1.1(0x7f1aec8d5ac8, 0xc00037a540, 0xc000366e00)\n\t/go/src/github.com/pomerium/pomerium/internal/log/middleware.go:113 +0x190\nnet/http.HandlerFunc.ServeHTTP(0xc000273350, 0x7f1aec8d5ac8, 0xc00037a540, 0xc000366e00)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\ngithub.com/pomerium/pomerium/internal/log.UserAgentHandler.func1.1(0x7f1aec8d5ac8, 0xc00037a540, 0xc000366e00)\n\t/go/src/github.com/pomerium/pomerium/internal/log/middleware.go:97 +0x190\nnet/http.HandlerFunc.ServeHTTP(0xc0002733b0, 0x7f1aec8d5ac8, 0xc00037a540, 0xc000366e00)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\ngithub.com/pomerium/pomerium/internal/log.RemoteAddrHandler.func1.1(0x7f1aec8d5ac8, 0xc00037a540, 0xc000366e00)\n\t/go/src/github.com/pomerium/pomerium/internal/log/middleware.go:81 +0xc4\nnet/http.HandlerFunc.ServeHTTP(0xc000273410, 0x7f1aec8d5ac8, 0xc00037a540, 0xc000366e00)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\ngithub.com/pomerium/pomerium/internal/log.HeadersHandler.func1.1(0x7f1aec8d5ac8, 0xc00037a540, 0xc000366e00)\n\t/go/src/github.com/pomerium/pomerium/internal/log/middleware.go:190 +0x10f\nnet/http.HandlerFunc.ServeHTTP(0xc000273470, 0x7f1aec8d5ac8, 0xc00037a540, 0xc000366e00)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\ngithub.com/pomerium/pomerium/internal/middleware.SetHeaders.func1.1(0x7f1aec8d5ac8, 0xc00037a540, 0xc000366d00)\n\t/go/src/github.com/pomerium/pomerium/internal/middleware/middleware.go:22 +0x388\nnet/http.HandlerFunc.ServeHTTP(0xc0001d40c0, 0x7f1aec8d5ac8, 0xc00037a540, 0xc000366d00)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\ngithub.com/pomerium/pomerium/internal/log.AccessHandler.func1.1(0x109f6e0, 0xc0003880a0, 0xc000366d00)\n\t/go/src/github.com/pomerium/pomerium/internal/log/middleware.go:168 +0x1dc\nnet/http.HandlerFunc.ServeHTTP(0xc0001d40e0, 0x109f6e0, 0xc0003880a0, 0xc000366d00)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\ngithub.com/pomerium/pomerium/internal/log.NewHandler.func1.1(0x109f6e0, 0xc0003880a0, 0xc000366c00)\n\t/go/src/github.com/pomerium/pomerium/internal/log/middleware.go:23 +0x3b7\nnet/http.HandlerFunc.ServeHTTP(0xc00024c1c0, 0x109f6e0, 0xc0003880a0, 0xc000366c00)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\ngo.opencensus.io/plugin/ochttp.(*Handler).ServeHTTP(0xc00057fa60, 0x109f6e0, 0xc0003880a0, 0xc000366a00)\n\t/go/pkg/mod/go.opencensus.io@v0.22.2/plugin/ochttp/server.go:92 +0x2b9\ngithub.com/pomerium/pomerium/internal/telemetry/metrics.HTTPMetricsHandler.func1.1(0x109e620, 0xc00020e000, 0xc000366900)\n\t/go/src/github.com/pomerium/pomerium/internal/telemetry/metrics/http.go:131 +0x35a\nnet/http.HandlerFunc.ServeHTTP(0xc000273590, 0x109e620, 0xc00020e000, 0xc000366900)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\ngithub.com/gorilla/mux.(*Router).ServeHTTP(0xc000478000, 0x109e620, 0xc00020e000, 0xc000366500)\n\t/go/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:212 +0xe2\nnet/http.serverHandler.ServeHTTP(0xc00020e1c0, 0x109e620, 0xc00020e000, 0xc000366500)\n\t/usr/local/go/src/net/http/server.go:2802 +0xa4\nnet/http.(*conn).serve(0xc0000cba40, 0x10a1860, 0xc0003570c0)\n\t/usr/local/go/src/net/http/server.go:1890 +0x875\ncreated by net/http.(*Server).Serve\n\t/usr/local/go/src/net/http/server.go:2928 +0x384"
}
```

There are no problem if I start from a fresh session from within private browsing: I can login and logout without any problem, so I suppose it's coming from the cookie on my browser.

**Comment by victornoel** [comment]
For the record, resetting the cookie secret forces users to re-login and make the problem disappear.

**Comment by desimone** [comment]
Trying to track down why `AccessToken` is nil here. https://github.com/pomerium/pomerium/blob/0-5-0/internal/identity/google.go#L103

**Comment by desimone** [comment]
This is a bug, and should be hotfixed. Standby

**Comment by desimone** [comment]
See v0.6.3
