### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Vad1mo** [pomerium/pomerium#634]
## What happened?
I got an exception logged and I am not sure how critical it is.

## How'd it happen?
I have set in config/secret `pomerium_debug: true` 

## What's your environment like?
k8s with pomerium-helm and traefik forwardauth

## What's your config.yaml?

```config.yaml
  - config:
          rootDomain: "corp.stage.example.com"
          generateTLS: true
          insecure: true #default false
          policy:
            - from: "https://dashboard.stage.example.com"
              to: "http://traefik-headless-service:9000"
              allowed_users:
                - "user@gmail.com"
            - from: "https://whoami.stage.example.com"
              to: "https://whoami.stage.example.com"
              allowed_users:
                - "user@gmail.com"
      - authenticate:
          idp:
            provider: "gitlab"
            url: "https://gitlab.com"
            clientID: "xxx"
            clientSecret: "xxx"
      - forwardAuth:
          enabled: true
      - ingress:
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.tls: "true"
          secretName: pomerium-ingress-tls
      - cache:
          replicaCount: 2

```

## What did you see in the logs?

```logs

  |   |   | 2020-04-29 15:47:09 | 1:47PM INF internal/httputil: http server started addr=:443
-- | -- | -- | -- | --
  |   |   | 2020-04-29 15:47:09 | 1:47PM DBG internal/grpc: added custom certificate authority
  |   |   | 2020-04-29 15:47:09 | 1:47PM INF cmd/pomerium version=v0.7.5+5f0c137
  |   |   | 2020-04-29 15:47:08 | /go/pkg/mod/github.com/spf13/viper@v1.6.3/viper.go:363 +0x2e7
  |   |   | 2020-04-29 15:47:08 | created by github.com/spf13/viper.(*Viper).WatchConfig.func1
  |   |   | 2020-04-29 15:47:08 | /go/pkg/mod/github.com/spf13/viper@v1.6.3/viper.go:385 +0x230
  |   |   | 2020-04-29 15:47:08 | github.com/spf13/viper.(*Viper).WatchConfig.func1.1(0xc000558000, 0xc000164090, 0x7ffea414c0e9, 0x19, 0x7ffea414c0e9, 0x19, 0xc00017c000, 0xc000353320)
  |   |   | 2020-04-29 15:47:08 | /go/src/github.com/pomerium/pomerium/cmd/pomerium/main.go:93 +0x124
  |   |   | 2020-04-29 15:47:08 | main.run.func1(0xc0004d07b0, 0x2d, 0x10)
  |   |   | 2020-04-29 15:47:08 | /go/src/github.com/pomerium/pomerium/config/options.go:554 +0x320
  |   |   | 2020-04-29 15:47:08 | github.com/pomerium/pomerium/config.HandleConfigUpdate(0x7ffea414c0e9, 0x19, 0xc0003a1500, 0xc000765e78, 0x2, 0x2, 0xc000635f50)
  |   |   | 2020-04-29 15:47:08 | /go/src/github.com/pomerium/pomerium/authorize/authorize.go:93 +0x16c
  |   |   | 2020-04-29 15:47:08 | github.com/pomerium/pomerium/authorize.(*Authorize).UpdateOptions(0x0, 0x1, 0x113ccd9, 0x5, 0xc0004d0c00, 0x2c, 0xc000036009, 0x5, 0x113bc8e, 0x4, ...)
  |   |   | 2020-04-29 15:47:08 | goroutine 43 [running]:
  |   |   | 2020-04-29 15:47:08 |  
  |   |   | 2020-04-29 15:47:08 | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xdac25c]
  |   |   | 2020-04-29 15:47:08 | panic: runtime error: invalid memory address or nil pointer dereference
  |   |   | 2020-04-29 15:47:08 | {"level":"debug","ip":"100.64.0.192","user_agent":"kube-probe/1.17","req_id":"f4c9f693-cb0d-ac1c-d36f-fd76eb0c4785","duration":0.047229,"size":66,"status":200,"method":"GET","service":"proxy","host":"100.64.0.187:443","path":"/ping","time":"2020-04-29T13:47:08Z","message":"http-request"}
  |   |   | 2020-04-29 15:47:08 | 1:47PM INF authorize: updating options checksum=4d7510b3d40d32e5
  |   |   | 2020-04-29 15:47:08 | 1:47PM DBG config: checksum change new-checksum=4d7510b3d40d32e5 old-checksum=ecc0ca36e2eaf5ce
  |   |   | 2020-04-29 15:47:08 | {"level":"info","file":"/etc/pomerium/..2020_04_29_13_47_08.747769464","time":"2020-04-29T13:47:08Z","message":"cmd/pomerium: config file changed"}
  |   |   | 2020-04-29 15:47:08 | {"level":"debug","ip":"100.64.0.192","user_agent":"kube-probe/1.17","req_id":"07253eda-a331-5240-fc76-2bdd7d2a828f","duration":0.046066,"size":66,"status":200,"method":"GET","service":"proxy","host":"100.64.0.187:443","path":"/ping","time":"2020-04-29T13:47:08Z","message":"http-request"}
  |   |   | 2020-04-29 15:47:06 | 1:47PM INF authorize: ecdsa public key PublicKey=LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFRmNUa05xeUF4dEp0c29vaXhyaVJDOHZPT3RyWQpaTllBVkZ0OVM0eFNEOEExSmZNNElQTjdGbnY3Wlp3d3J5bWFEYWo5cmhMYXVDQkZQWDhZYy9xemVBPT0KLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
  |   |   | 2020-04-29 15:47:06 | 1:47PM INF authorize: updating options checksum=eccd314264b62c0a
  |   |   | 2020-04-29 15:47:06 | 1:47PM DBG config: checksum change new-checksum=eccd314264b62c0a old-checksum=4d78ebc75251eb21
  |   |   | 2020-04-29 15:47:06 | {"level":"warn","Addr":":5443","GRPCAddr":":5443","time":"2020-04-29T13:47:06Z","message":"config: default http handler changed"}
  |   |   | 2020-04-29 15:47:06 | {"level":"info","file":"/etc/pomerium/..2020_04_29_13_47_06.907672721","time":"2020-04-29T13:47:06Z","message":"cmd/pomerium: config file changed"}


```

**Comment by Lumexralph** [comment]
@Vad1mo Thanks for trying out Pomerium. Can you please help with how to reproduce the error?

**Comment by Vad1mo** [comment]
I deployed pomerium with helm on k8s. Then I went to change the config of promerium.  Edit the secret and added `pomerium_debug: true` when the application picked up the change is printed this on the screen. 

If you want I can show this to you live, just drop me a message on slack.

**Comment by Lumexralph** [comment]
I had a call with @Vad1mo  today, he showed me the error.

It happens when you start pomerium up in the k8s cluster. Everything is fine until when you change the configuration file in the cluster and save the file, pomerium picks the file changes and on updating, this leads to the null pointer or invalid memory error.

Could it be that `opts` wasn’t populated when the `UpdateOptions`  method was called?
@desimone @travisgroth

**Comment by travisgroth** [comment]
I also saw this or something very similar last week during some other testing.  I haven't had time to reproduce yet.  

@Lumexralph an empty config should be rejected on reload, though I haven't tried that in some time.  

@Vad1mo it seems you are _not_ using the operator, correct?

**Comment by Vad1mo** [comment]
@travisgroth correct. I increased the debug level while the system was already running. `Kubectl edit secret Pomerium `

**Comment by travisgroth** [comment]
@Vad1mo what kubernetes provider are you using?  I'm trying to repro this locally and cannot, for some reason.

**Comment by Vad1mo** [comment]
Not sure, but usually I use SCW(Scaleway), k3s or k3d for testing.

**Comment by travisgroth** [comment]
Was SCW what you originally encountered this with?

**Comment by Vad1mo** [comment]
I think so but I am not entirely sure.

**Comment by Vad1mo** [comment]
I can give it a try with k3s/k3d

**Comment by travisgroth** [comment]
No worries - I was wondering if it was somehow provider specific but I just managed to reproduce it.  Thanks.

**Comment by travisgroth** [comment]
Also backported to 0.7.6 in #654
